# conda env create -f environment-macos.yaml
# conda env update -n dl-course --file environment-macos.yaml
name: dl-course
channels:
- pytorch
- conda-forge
dependencies:
- python=3.10
- pip
- pytorch::pytorch=2.0.1
- torchvision>=0.15.2
- torchaudio>=2.0.2
- pip:
  - lightning==2.0.9
  - matplotlib==3.8.0
  - seaborn==0.12.2
  - plotly==5.17.0
  - jupyter
  - notebook
  - aim==3.17.5
